Install crowbar-openstack before neutron
neutron installation fails because it depends on crowbar-openstack cookbook.
Th error message is:

    Installing barclamp neutron from /opt/dell/barclamps/neutron
    ERROR: /opt/dell/barclamps/neutron knife cookbook upload -o . neutron -V -k /etc/chef/webui.pem -u chef-webui upload failed.  Aborting; examine /var/log/crowbar/barclamp_install/neutron.log for more info.

And neutron.log content is:

    Uploading neutron        [1.0.0]
    ERROR: Cookbook neutron depends on cookbook crowbar-openstack version >= 0.0.0,
    ERROR: which is not currently being uploaded and cannot be found on the server.

(cherry picked from commit 874f599cbba830a0208c7bcac5f0348a9e4017e8)