Install crowbar-openstack before neutron
neutron installation fails because it depends on crowbar-openstack cookbook.
The error message is:

    Installing barclamp neutron from /opt/dell/barclamps/neutron
    ERROR: /opt/dell/barclamps/neutron knife cookbook upload -o . neutron -V -k /etc/chef/webui.pem -u chef-webui upload failed.  Aborting; examine /var/log/crowbar/barclamp_install/neutron.log for more info.

And neutron.log content is:

    Uploading neutron        [1.0.0]
    ERROR: Cookbook neutron depends on cookbook crowbar-openstack version >= 0.0.0,
    ERROR: which is not currently being uploaded and cannot be found on the server.

**This commit is forward-ported from 6c8cf21ff4cd54265ed7bdba1fb81b56c8679da2**